# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitLs < Formula
  desc "list the files in the current directory along with a useful summary and helpful hyperlinks."
  homepage "https://github.com/llimllib/git-ls"
  version "7.1.1"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/llimllib/git-ls/releases/download/v7.1.1/git-ls_Darwin_x86_64.tar.gz"
      sha256 "9b9a8842acb41681e62b524e875c235c6b39c254c8c019c1f050663a604dd2d0"

      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/llimllib/git-ls/releases/download/v7.1.1/git-ls_Darwin_arm64.tar.gz"
      sha256 "5b53102aa4b44447c327954e293b5da2c3dfa9036cc8ac63367afe56382d3379"

      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/llimllib/git-ls/releases/download/v7.1.1/git-ls_Linux_x86_64.tar.gz"
      sha256 "3abcbe86bb200f743e513c6f42f95aa52075eb393ae2ca755a2a32edf8e0ea9c"
      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/llimllib/git-ls/releases/download/v7.1.1/git-ls_Linux_arm64.tar.gz"
      sha256 "db39f48a2ebe4f07ab1a389e5d77297f4a93c9d57731b08c900ba233e21e9128"
      define_method(:install) do
        bin.install "git-ls"
        man1.install "manpage/git-ls.1"
      end
    end
  end
end
