# This file was generated by GoReleaser. DO NOT EDIT.
cask "aver" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/aver"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "56ae72c01b2ce1944c68eecee20a37c3f7099489059119bc46be128f69be31f8"
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ebf5e1d0b9d259f241623593766371d7d7a519d0606ff349df915f6408cc2183"
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "efff3f88edfe86bf92610db9233a31a20ea2f50c39132de7fd81177357eed3b0"
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a04295be1b1b27c81530fcb683bc132f03e74488d8573c96bec19ed4e07190c5"
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aver"
  desc "A GitHub Actions version checker. Scans your GitHub actions workflow files and reports outdated versions."
  homepage "https://github.com/llimllib/aver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aver"

  # No zap stanza required
end
