# This file was generated by GoReleaser. DO NOT EDIT.
cask "aver" do
  name "aver"
  desc "A GitHub Actions version checker. Scans your GitHub actions workflow files and reports outdated versions."
  homepage "https://github.com/llimllib/aver"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aver"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/llimllib/aver"
      sha256 "bca3c53f886023c6dd4804a14921b2624c3ab7b426d615aec84a53e6af9bc7e0"
    end
    on_arm do
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/llimllib/aver"
      sha256 "3323fe2d3a29604de4e06a0dce4587b5c8771cbc96e116ed76952e3fc7a99ca1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_linux_amd64.tar.gz",
        verified: "github.com/llimllib/aver"
      sha256 "f7686d5b33175a7f67c5cf7aae32c4de04919d5eaef955aee168ec4f98ce912e"
    end
    on_arm do
      url "https://github.com/llimllib/aver/releases/download/v#{version}/aver_#{version}_linux_arm64.tar.gz",
        verified: "github.com/llimllib/aver"
      sha256 "f0d794c83c2deaf289860d285a44b58da2fd704502522d797333664750096c3e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aver"]
    end
  end

  # No zap stanza required
end
