# This file was generated by GoReleaser. DO NOT EDIT.
cask "brightlantern" do
  app "Bright Lantern.app"

  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "abd5f1cd945b67da36fefd8432d2c54e9b18b99abb4fdd7af077a686ef0dc712"
      url "https://github.com/llimllib/brightlantern/releases/download/v#{version}/brightlantern_#{version}_macos_arm64.zip"
    end
  end

  name "brightlantern"
  desc "Search and read agent sessions from pi and Claude Code"
  homepage "https://github.com/llimllib/brightlantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "#{appdir}/Bright Lantern.app/Contents/MacOS/brightlantern"

  # No zap stanza required

  caveats <<~EOS
    Open Bright Lantern from Applications once. It finds your agent
    sessions, indexes them, and keeps indexing at login with no window
    open. `brightlantern` on the command line uses the same index.

    Titles are generated on-device and need Apple Intelligence turned on.
  EOS
end
