# This file was generated by GoReleaser. DO NOT EDIT.
cask "crun" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/crun"]
    end
  end

  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "a51477cc0e9daf1973e292304fa5bba24b7fab9088b07900fe75a6f5b778d4a0"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "1f22c91d04c14d344a34764d2b3bd30282de3e510fde466635d386006e50e4f9"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "23faff4dd40948b6fa90a0a62762acde0e0eaa8686e41dbe46ac2a74c94789ec"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "8944eeceb274a06fa5e91ea0538d71e0c7f95f45596c861e5ece049b12095b52"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "crun"
  desc "Run commands concurrently"
  homepage "https://github.com/llimllib/crun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crun"

  # No zap stanza required
end
