# This file was generated by GoReleaser. DO NOT EDIT.
cask "crun" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "4a6eab922e90ce9024179dcca0cc7b486d9e5020da9e22e0bf1a51e633901dd0"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/crun"
    end
    on_arm do
      sha256 "817f3375c5f1c3f062c7705f20b023c9b89711f976c1d4082842e2f1303cdad7"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/crun"
    end
  end

  on_linux do
    on_intel do
      sha256 "38fff8c26e54b18a0faa32daf00799529afa9cd973557462cf49bfa4b93d095f"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/crun"
    end
    on_arm do
      sha256 "2fa9ba00969fff1fb46cbe3476e6894268567421f4436aba0b4414a42fd7ddc3"
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/llimllib/crun"
    end
  end

  name "crun"
  desc "Run commands concurrently"
  homepage "https://github.com/llimllib/crun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crun"]
    end
  end

  # No zap stanza required

end
