# This file was generated by GoReleaser. DO NOT EDIT.
cask "crun" do
  name "crun"
  desc "Run commands concurrently"
  homepage "https://github.com/llimllib/crun"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crun"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/crun"
      sha256 "0f284f10376f8113aff4aae85f818b66ef27f0f3b6703969b81c7fc3d923e5ce"
    end
    on_arm do
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/crun"
      sha256 "ce0ccce4e827e4828f2320a42aaeb5d20d564f90f24940dd0d02247a8825fd22"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/crun"
      sha256 "36bbcb0cac8382cf103fef55d5d90eb352637166f5dc11c58a8a834a9f13cf25"
    end
    on_arm do
      url "https://github.com/llimllib/crun/releases/download/v#{version}/crun-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/llimllib/crun"
      sha256 "4ab37c08b515f8c300636b7a77cb161fbbd3496660e94eb0d6539598c0ac1d80"
    end
  end

  # No zap stanza required
end
