# This file was generated by GoReleaser. DO NOT EDIT.
cask "devd" do
  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "784495c9c8629bf789314140e83393ce67848ceb782c78a6be5d326b1c54fe37"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6ac3ee60ddd701d3ac3b6b796bb958dfa20628faf2ad4214b88066eb4fd6200"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59dcf9115a7b95e422e6cddf3bc6db17750422404cf7f1ba739f04e46894ce66"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ed1a948020f48d61151fc9914e89949d40995e13847d2fdbc12d0a47df506a9"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devd"
  desc " A local webserver for developers"
  homepage "https://github.com/llimllib/devd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devd"]
    end
  end

  # No zap stanza required
end
