# This file was generated by GoReleaser. DO NOT EDIT.
cask "devd" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devd"]
    end
  end

  version "0.11.2"

  on_macos do
    on_arm do
      sha256 "e06c82558fc183a3d046ec370bc4b975c8841b84615a83068ff29a6961952034"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "144300b0c87494596de9fd0dcb8d9e9e0abe83298e480aa8fd54d3a28ffc97f4"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a6f8339cffea896707d47e873c6a41a68000a3032264c7134e4f25da1a037993"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6dcf1364d3c905f32fabdd12a08fe7cd2608cb39ed06f5c1a9ca4001bdb240c"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devd"
  desc " A local webserver for developers"
  homepage "https://github.com/llimllib/devd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devd"

  # No zap stanza required
end
