# This file was generated by GoReleaser. DO NOT EDIT.
cask "devd" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "a15deb7b3b4a8b96e28341369164be03a3b360b79c0b9af8feedddd50498ed6b"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/llimllib/devd"
    end
    on_arm do
      sha256 "5cf3d77f99e36b3989600fad76237156f51c4a577b2c3d78e12e7994ee2ee739"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/llimllib/devd"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f01390257907468aebdab991c226536cb442169d1a16df652f875c7ca1275d6"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_amd64.tar.gz",
        verified: "github.com/llimllib/devd"
    end
    on_arm do
      sha256 "70d82fbcd0ae88a2868c7022747370349db9b1a83e8cc3796014f25e2d8f34da"
      url "https://github.com/llimllib/devd/releases/download/v#{version}/devd_#{version}_linux_arm64.tar.gz",
        verified: "github.com/llimllib/devd"
    end
  end

  name "devd"
  desc " A local webserver for developers"
  homepage "https://github.com/llimllib/devd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devd"]
    end
  end

  # No zap stanza required

end
