# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdriver" do
  name "mdriver"
  desc "Streaming markdown printer for the terminal with syntax highlighting"
  homepage "https://github.com/llimllib/mdriver"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdriver"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "08ff4a8cbdc2b42ff496f4da3333207e0f3e7db4968ae0e9699ed7078ebdeabd"
    end
    on_arm do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "3902863d446add770c132f8a01c12ce47455540c642ef893f4aa1b5eee093b6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "a408eee829a7796f2e67a1b21356522f6aea3174b630f3289b46f6f60f0260db"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdriver"]
    end
  end

  # No zap stanza required
end
