# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdriver" do
  name "mdriver"
  desc "Streaming markdown printer for the terminal with syntax highlighting"
  homepage "https://github.com/llimllib/mdriver"
  version "0.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdriver"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "502ce4c5881ae1e78e67346349af7adce812ecf4d538ff4553111e91c01d20a8"
    end
    on_arm do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "9b7e462252baaca395abda9ab33612d324845d98b41205b3ae287d6e8ddadc3d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
      sha256 "929ccc11563a7f494c9a9a10928e7f6bbeabdb1d6ec5efc82a8c59c21b09fb65"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdriver"]
    end
  end

  # No zap stanza required
end
