# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdriver" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "76e49f832ecfb81a42019a1f7df0e37d8c6855882115e31ee287a0b413f23018"
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
    end
    on_arm do
      sha256 "24c76b18146c9fd4acd751bece0b06684d2b1cccb7e1ddf7597414ea12fdff1b"
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/mdriver"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab652c887e551ad7df911ee40a4b862936659f2d7bf66c2c4624e3d9e0af4a0f"
      url "https://github.com/llimllib/mdriver/releases/download/v#{version}/mdriver-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/mdriver"
    end
  end

  name "mdriver"
  desc "Streaming markdown printer for the terminal with syntax highlighting"
  homepage "https://github.com/llimllib/mdriver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdriver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdriver"]
    end
  end

  # No zap stanza required

end
