# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-review" do
  name "pr-review"
  desc "AI-powered code review using multiple specialized agents"
  homepage "https://github.com/llimllib/pr-review"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pr-review"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "a97a2241cc20741e633044457519af730979bfb15e2e40a5eca7070ed3e919dc"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "bb49bbe1346513e8e9e08e67761a7857a88dc090a941b060b31d3a7b342fd88f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "78f6121516f271852afe131fad9573b97b923bc866c2d645bc08bb8b8804c42a"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "ae39fada9bca02792ad170d8a06c6161f4c8d008049c7285b9b2a3788a0e2c47"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-review"]
    end
  end

  # No zap stanza required
end
