# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-review" do
  name "pr-review"
  desc "AI-powered code review using multiple specialized agents"
  homepage "https://github.com/llimllib/pr-review"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pr-review"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "a68e75654629b3afff445349667b1ab0629cd665f7e78d81494badc6c7d49c21"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "c66ae2257944c2f6cf2ddb47335159150495f3d97b16d13e4692504ad17a7e7e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "34b0a5518d489a23025fd2c4cc2f316d9dcc935bb198b912cc96765c4375c9c1"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "dfa6cc45b84e17bfc940f73f7e62c08e118db1504f3002dc716f5fef901eb148"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-review"]
    end
  end

  # No zap stanza required
end
