# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-review" do
  name "pr-review"
  desc "AI-powered code review using multiple specialized agents"
  homepage "https://github.com/llimllib/pr-review"
  version "3.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pr-review"

  on_macos do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "7b8fee81242fd9b5a359ead7a895114c55ad377e51b6778210ae45c7bad09ed1"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-darwin-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "9152097e088b33a0ee86f3e7530ab460ba48c3f49179a12fc725405d688a0b6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-amd64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "1f7ce84a90a69a191a53af562746d238e8e505baa94c4910f96d09206ad191b9"
    end
    on_arm do
      url "https://github.com/llimllib/pr-review/releases/download/v#{version}/pr-review-v#{version}-linux-arm64.tar.gz",
        verified: "github.com/llimllib/pr-review"
      sha256 "81994a15813b7fa5cff74fce51f84e93b9cf72bb9b9310b1348cc81a7dac8f71"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-review"]
    end
  end

  # No zap stanza required
end
