# This file was generated by GoReleaser. DO NOT EDIT.
cask "spireweb" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}"]
    end
  end

  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "0f2b523e547d04790a45bf6f7ee0f887ff4d1c380ce3e19fd74125d9b14ec8cf"
      url "https://github.com/llimllib/spireweb/releases/download/v#{version}/spireweb_#{version}_macos_arm64.tar.gz"
    end
  end

  name "spireweb"
  desc "Search and read agent sessions from pi and Claude Code"
  homepage "https://github.com/llimllib/spireweb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spireweb"

  # No zap stanza required

  caveats <<~EOS
    spireweb indexes your agent sessions on first run.

    The first semantic search compiles Metal shaders and takes about
    15 seconds; subsequent runs are instant until macOS evicts its
    shader cache.
  EOS
end
